//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""Manager"",
            ""id"": ""f4f8a2ab-8301-428e-8b0b-145726b53a52"",
            ""actions"": [
                {
                    ""name"": ""Any"",
                    ""type"": ""Button"",
                    ""id"": ""d9b55a2b-ba70-49f9-bed2-403dc1f44f39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a1ccec05-3527-471f-bef0-caa0df2b45d4"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Any"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Manager
        m_Manager = asset.FindActionMap("Manager", throwIfNotFound: true);
        m_Manager_Any = m_Manager.FindAction("Any", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Manager
    private readonly InputActionMap m_Manager;
    private List<IManagerActions> m_ManagerActionsCallbackInterfaces = new List<IManagerActions>();
    private readonly InputAction m_Manager_Any;
    public struct ManagerActions
    {
        private @GameInput m_Wrapper;
        public ManagerActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Any => m_Wrapper.m_Manager_Any;
        public InputActionMap Get() { return m_Wrapper.m_Manager; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ManagerActions set) { return set.Get(); }
        public void AddCallbacks(IManagerActions instance)
        {
            if (instance == null || m_Wrapper.m_ManagerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ManagerActionsCallbackInterfaces.Add(instance);
            @Any.started += instance.OnAny;
            @Any.performed += instance.OnAny;
            @Any.canceled += instance.OnAny;
        }

        private void UnregisterCallbacks(IManagerActions instance)
        {
            @Any.started -= instance.OnAny;
            @Any.performed -= instance.OnAny;
            @Any.canceled -= instance.OnAny;
        }

        public void RemoveCallbacks(IManagerActions instance)
        {
            if (m_Wrapper.m_ManagerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IManagerActions instance)
        {
            foreach (var item in m_Wrapper.m_ManagerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ManagerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ManagerActions @Manager => new ManagerActions(this);
    public interface IManagerActions
    {
        void OnAny(InputAction.CallbackContext context);
    }
}
